ui: mocha-bdd
browsers:
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
  - name: ie
    version: [11, latest]
  - name: iphone
    version: [7.0, 8.0, 9.0, latest]